modLoader="javafml" 
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="zombienation"
version="1.16.5-1.0.3.0"
displayName="Zombienation"
displayURL="https://www.curseforge.com/minecraft/mc-mods/zombienation"
authors="Mad Alchemist"
credits="ewallee"
description='''
Do you think vanilla zombies are boring?
This mod adds more zombies, with different faces, voices,
and special abilities! More features coming soon!
'''
logoFile="logo.png"

[[dependencies.zombienation]]
    modId="forge" 
    mandatory=true 
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zombienation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"