modLoader="javafml" 
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="betterzombies"
version="1.16.5-0.0.0.0"
displayName="Better Zombies Mod"
displayURL=""
authors="Mad Alchemist"
credits="Zombies"
description='''
Do you think that vanilla zombies are boring? Me too!
From now zombies will have different look and behavior,
they will not burn in sunlight, and they will infect!
Survival game will become harder!
'''
logoFile="logo.png"

[[dependencies.betterzombies]] 
    modId="forge" 
    mandatory=true 
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterzombies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"